### ISSUE TITLE
3 FAQ's added which may help people running into problems with Fail2Ban

### ISSUE THREAD

**Issue by mitchellkrogza** [sebres/fail2ban#8]
See https://github.com/mitchellkrogza/fail2ban-wiki/blob/master/Properly%20fail2ban%20configuration.md for suggested changes to Wiki

**Comment by sebres** [comment]
> you should edit paths-common.conf or paths-debian.conf

Please correct this, because conflict with my statement "You should avoid to change .conf files, created by fail2ban installation."

So never change `.conf` files, all the changes should going to corresponding `.local` file, that will be automatically loaded above...

**Comment by mitchellkrogza** [comment]
Thanks @sebres have updated that FAQ to instruct on creating .local files instead.

**Comment by sebres** [comment]
>  I messed up Fail2Ban during Testing and blocked out my own IP address, how do I completely reset Fail2Ban to get it off to a clean start?

Well the suggested way is even imaginable, but ...
- you don't need to stop fail2ban, you can just unban it manually - `fail2ban-client set <JAIL> unbanip <IP>`, it will remove all the entries for this IP from sqlite-database also;
- resetting of the log-files are unnecessary at all also, because fail2ban will ignore already processed entries.
- in the newer version (0.10th branch) you can even unban it in all jails at once, use `fail2ban-client unban <IP> ... <IP>` (works similar to example above. but for all jails); see https://github.com/fail2ban/fail2ban/pull/1557 provide this functionality.

**Comment by sebres** [comment]
> Fail2Ban will not start and is giving me the following error message "Job for fail2ban.service failed. See 'systemctl status fail2ban.service' and 'journalctl -xn' for details." but checking those does not help me trace where my error is.

The suggested kind of error-resolving is rather for heavy debugging. For normally usage, you can see the same error-message in the journal log of fail2ban.service - so `journalctl` together with `fail2ban.log` are your friends.

**Comment by mitchellkrogza** [comment]
I found this solution particular helpful myself when fail2ban would not start. I found journalctl and fail2ban.log not very clear and then found the solution to starting the client in verbose mode which within seconds pointed me to the exact jail causing a problem with a much clearer error message. Perhaps a lot of this has changed in 0.10 ??? I will start testing 0.10 branch and try moving off 0.9.3 but perhaps some of these FAQ's may still help people with 0.8x and 0.9x versions which they installed via their distro's repositories?

**Comment by sebres** [comment]
No, I thing it is good so, but I would firstly starting with something like "take a look in journal log of fail2ban.service (e. g. `journalctl -ru fail2ban`) , and if you find and fix error, reload fail2ban". 
And only hereafter start heavydebug error search.

**Comment by mitchellkrogza** [comment]
Thanks @sebres I have amended that FAQ to be more clear on that.

**Comment by sebres** [comment]
Merged in fail2ban-wiki.

BTW you can contribute there directly... (just don't overdo it ;)
