### ISSUE TITLE
Suggest adding a branch called "contributions"

### ISSUE THREAD

**Issue by mitchellkrogza** [sebres/fail2ban#9]
As it is not possible to fork a copy of a wiki git, I suggest you can maybe add a branch to this called "contributions" / "contributors" where people can push changes to?

**Comment by sebres** [comment]
It seems to be impossible...

**Comment by mitchellkrogza** [comment]
Does seem rather impossible, I found this which led to suggest a branch.
https://help.github.com/articles/adding-and-editing-wiki-pages-locally/
